version: "3.4"

services:
  expresslocallibrarytutorial:
    image: cartservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3002:3000
